<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-13M4B933" failures="1" tests="3" name="Regresssion" time="2.824" errors="0" timestamp="2025-06-05T06:46:47 IST">
  <testcase classname="practice.api.rest1.Testing1" name="ReqS1" time="0.698"/>
  <testcase classname="practice.api.rest1.Testing1" name="SubPost1" time="2.071"/>
  <testcase classname="practice.api.rest1.Testing1" name="ResT1" time="0.001">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;io.restassured.response.Response.statusCode()&amp;quot; because &amp;quot;this.Res&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "io.restassured.response.Response.statusCode()" because "this.Res" is null
at practice.api.rest1.Testing1.ResT1(Testing1.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- ResT1 -->
  <testcase classname="practice.api.rest1.Testing1" name="ReqF1" time="0.0">
    <ignored/>
  </testcase> <!-- ReqF1 -->
  <testcase classname="practice.api.rest1.Testing1" name="SubGet1" time="0.0">
    <ignored/>
  </testcase> <!-- SubGet1 -->
</testsuite> <!-- Regresssion -->
